version: '3.8'
services:

  database:
    image: postgres:12-bullseye
    environment:
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network      

  adminer:
    image: adminer
    container_name: adminer_db
    ports:
      - "8091:8080"
    networks:
      - app-network      

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    ports:
      - "8081:8081"      
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    expose:
      - 4200        
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html:ro      
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
  frontend_dist:

